In [20]:
import pandas as pd
import numpy as np
from dateutil.parser import parse
from datetime import datetime
import csv
import matplotlib.pyplot as plt
import math
import seaborn as sns
from scipy import stats
plt.style.use('fivethirtyeight')
import warnings
from IPython.display import display_html
warnings.filterwarnings('ignore')
%matplotlib inline
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [21]:
ads_v7  = pd.read_csv('gs://aes-datahub-0001-raw/OMS/IPL/ADS_V7.csv')
ads = ads_v7[ads_v7['EVENT']=='STORM']
ads=ads[['OUTAGE_ID', 'LAT', 'LONG']]
ads.reset_index(drop=True,inplace=True)
ads.head()

    OUTAGE_ID        LAT       LONG
0  2001317842  39.724871 -86.037147
1  2001317865  39.896820 -86.145802
2  2001317856  39.543034 -86.573913
3  2001317899  39.787152 -86.252024
4  2001317873  39.631311 -86.375051

In [22]:
ads['Marker1_LAT'] =  39.9613 
ads['Marker2_LAT'] = 39.8971
ads['Marker3_LAT'] = 39.9060
ads['Marker4_LAT'] = 39.9024
ads['Marker5_LAT'] = 39.8960
ads['Marker6_LAT'] = 39.8339
ads['Marker7_LAT'] = 39.8412
ads['Marker8_LAT'] = 39.8381
ads['Marker9_LAT'] = 39.8386
ads['Marker10_LAT'] = 39.7579
ads['Marker11_LAT'] = 39.7621
ads['Marker12_LAT'] = 39.7621
ads['Marker13_LAT'] = 39.7695
ads['Marker14_LAT'] = 39.6617
ads['Marker15_LAT'] = 39.6639
ads['Marker16_LAT'] = 39.6702
ads['Marker17_LAT'] = 39.6744
ads['Marker18_LAT'] = 39.5909
ads['Marker19_LAT'] = 39.5295
ads['Marker20_LAT'] = 39.5475

ads['Marker1_LONG'] = -86.4034 
ads['Marker2_LONG'] = -86.3045
ads['Marker3_LONG'] = -86.2001
ads['Marker4_LONG'] = -86.0738
ads['Marker5_LONG'] = -85.9783
ads['Marker6_LONG'] = -86.3155
ads['Marker7_LONG'] = -86.2056
ads['Marker8_LONG'] = -86.0985
ads['Marker9_LONG'] = -85.9811
ads['Marker10_LONG'] = -86.3155
ads['Marker11_LONG'] = -86.2042
ads['Marker12_LONG'] = -86.0923
ads['Marker13_LONG'] = -85.9708
ads['Marker14_LONG'] = -86.2935
ads['Marker15_LONG'] = -86.1823
ads['Marker16_LONG'] = -86.0669
ads['Marker17_LONG'] = -85.9557
ads['Marker18_LONG'] = -86.4212
ads['Marker19_LONG'] = -86.5874
ads['Marker20_LONG'] = -86.2743

In [23]:
ads.head()

    OUTAGE_ID        LAT       LONG  Marker1_LAT  Marker2_LAT  Marker3_LAT  Marker4_LAT  Marker5_LAT  Marker6_LAT  Marker7_LAT  Marker8_LAT  Marker9_LAT  Marker10_LAT  Marker11_LAT  Marker12_LAT  Marker13_LAT  Marker14_LAT  Marker15_LAT  Marker16_LAT  Marker17_LAT  Marker18_LAT  Marker19_LAT  Marker20_LAT  Marker1_LONG  Marker2_LONG  Marker3_LONG  Marker4_LONG  Marker5_LONG  Marker6_LONG  Marker7_LONG  Marker8_LONG  Marker9_LONG  Marker10_LONG  Marker11_LONG  Marker12_LONG  Marker13_LONG  Marker14_LONG  Marker15_LONG  Marker16_LONG  Marker17_LONG  Marker18_LONG  Marker19_LONG  Marker20_LONG
0  2001317842  39.724871 -86.037147      39.9613      39.8971       39.906      39.9024       39.896      39.8339      39.8412      39.8381      39.8386       39.7579       39.7621       39.7621       39.7695       39.6617       39.6639       39.6702       39.6744       39.5909       39.5295       39.5475      -86.4034      -86.3045      -86.2001      -86.0738      -85.9783      -86.3155      -86.2056      -86.0985      -85.9811       -86.3155       -86.2042       -86.0923       -85.9708       -86.2935       -86.1823       -86.0669       -85.9557       -86.4212       -86.5874       -86.2743
1  2001317865  39.896820 -86.145802      39.9613      39.8971       39.906      39.9024       39.896      39.8339      39.8412      39.8381      39.8386       39.7579       39.7621       39.7621       39.7695       39.6617       39.6639       39.6702       39.6744       39.5909       39.5295       39.5475      -86.4034      -86.3045      -86.2001      -86.0738      -85.9783      -86.3155      -86.2056      -86.0985      -85.9811       -86.3155       -86.2042       -86.0923       -85.9708       -86.2935       -86.1823       -86.0669       -85.9557       -86.4212       -86.5874       -86.2743
2  2001317856  39.543034 -86.573913      39.9613      39.8971       39.906      39.9024       39.896      39.8339      39.8412      39.8381      39.8386       39.7579       39.7621       39.7621       39.7695       39.6617       39.6639       39.6702       39.6744       39.5909       39.5295       39.5475      -86.4034      -86.3045      -86.2001      -86.0738      -85.9783      -86.3155      -86.2056      -86.0985      -85.9811       -86.3155       -86.2042       -86.0923       -85.9708       -86.2935       -86.1823       -86.0669       -85.9557       -86.4212       -86.5874       -86.2743
3  2001317899  39.787152 -86.252024      39.9613      39.8971       39.906      39.9024       39.896      39.8339      39.8412      39.8381      39.8386       39.7579       39.7621       39.7621       39.7695       39.6617       39.6639       39.6702       39.6744       39.5909       39.5295       39.5475      -86.4034      -86.3045      -86.2001      -86.0738      -85.9783      -86.3155      -86.2056      -86.0985      -85.9811       -86.3155       -86.2042       -86.0923       -85.9708       -86.2935       -86.1823       -86.0669       -85.9557       -86.4212       -86.5874       -86.2743
4  2001317873  39.631311 -86.375051      39.9613      39.8971       39.906      39.9024       39.896      39.8339      39.8412      39.8381      39.8386       39.7579       39.7621       39.7621       39.7695       39.6617       39.6639       39.6702       39.6744       39.5909       39.5295       39.5475      -86.4034      -86.3045      -86.2001      -86.0738      -85.9783      -86.3155      -86.2056      -86.0985      -85.9811       -86.3155       -86.2042       -86.0923       -85.9708       -86.2935       -86.1823       -86.0669       -85.9557       -86.4212       -86.5874       -86.2743

In [37]:
def convert_kilometer_to_miles(x):
    if (math.isnan(lat)):
        return None
    else :
        x = x * 0.621371
        return x

In [25]:
# calculate distance from 2 lat long 
import math
def haversine(p1, p2):
    R = 6371     # earth radius in km
    p1 = [math.radians(v) for v in p1]
    p2 = [math.radians(v) for v in p2]

    d_lat = p2[0] - p1[0]
    d_lng = p2[1] - p1[1]
    a = math.pow(math.sin(d_lat / 2), 2) + math.cos(p1[0]) * math.cos(p2[0]) * math.pow(math.sin(d_lng / 2), 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    return R * c   # returns distance between p1 and p2 in km

In [26]:
# calculate minimum distance

def minimum_distance(lat, long, marker1_lat, marker2_lat, marker3_lat, marker4_lat, marker5_lat, marker6_lat, marker7_lat, marker8_lat, marker9_lat, marker10_lat, marker11_lat,
                     marker12_lat, marker13_lat, marker14_lat, marker15_lat, marker16_lat, marker17_lat, marker18_lat, marker19_lat, marker20_lat, marker1_long, marker2_long,
                     marker3_long, marker4_long, marker5_long, marker6_long, marker7_long, marker8_long, marker9_long, marker10_long, marker11_long, marker12_long, marker13_long,
                     marker14_long, marker15_long, marker16_long, marker17_long, marker18_long, marker19_long, marker20_long):
    import operator
    
    dist1 = haversine((lat,long), (marker1_lat, marker1_long))
    dist2 = haversine((lat,long), (marker2_lat, marker2_long))
    dist3 = haversine((lat,long), (marker3_lat, marker3_long))
    dist4 = haversine((lat,long), (marker4_lat, marker4_long))
    dist5 = haversine((lat,long), (marker5_lat, marker5_long))
    dist6 = haversine((lat,long), (marker6_lat, marker6_long))
    dist7 = haversine((lat,long), (marker7_lat, marker7_long))
    dist8 = haversine((lat,long), (marker8_lat, marker8_long))
    dist9 = haversine((lat,long), (marker9_lat, marker9_long))
    dist10 = haversine((lat,long), (marker10_lat, marker10_long))
    dist11 = haversine((lat,long), (marker11_lat, marker11_long))
    dist12 = haversine((lat,long), (marker12_lat, marker12_long))
    dist13 = haversine((lat,long), (marker13_lat, marker13_long))
    dist14 = haversine((lat,long), (marker14_lat, marker14_long))
    dist15 = haversine((lat,long), (marker15_lat, marker15_long))
    dist16 = haversine((lat,long), (marker16_lat, marker16_long))
    dist17 = haversine((lat,long), (marker17_lat, marker17_long))
    dist18 = haversine((lat,long), (marker18_lat, marker18_long))
    dist19 = haversine((lat,long), (marker19_lat, marker19_long))
    dist20 = haversine((lat,long), (marker20_lat, marker20_long))
    
    dist_list = [dist1, dist2, dist3, dist4, dist5, dist6, dist7, dist8, dist9, dist10, dist11, dist12, dist13, dist14, dist15, dist16, dist17, dist18, dist19, dist20]

    min_index, min_value = min(enumerate(dist_list), key=operator.itemgetter(1))
    
    if ( (math.isnan(lat)) | (math.isnan(long)) ):
        return None, None
    else :
        return min_value, min_index+1

In [27]:
ads['Min_Distance'], ads['Marker_Location'] = zip(*ads.apply(lambda row: minimum_distance(row['LAT'], row['LONG'], row['Marker1_LAT'], row['Marker2_LAT'],
                                                            row['Marker3_LAT'], row['Marker4_LAT'], row['Marker5_LAT'], row['Marker6_LAT'],
                                                            row['Marker7_LAT'], row['Marker8_LAT'], row['Marker9_LAT'], row['Marker10_LAT'], 
                                                            row['Marker11_LAT'], row['Marker12_LAT'], row['Marker13_LAT'], row['Marker14_LAT'],
                                                            row['Marker15_LAT'], row['Marker16_LAT'], row['Marker17_LAT'], row['Marker18_LAT'],
                                                            row['Marker19_LAT'], row['Marker20_LAT'], row['Marker1_LONG'], row['Marker2_LONG'],
                                                            row['Marker3_LONG'], row['Marker4_LONG'], row['Marker5_LONG'], row['Marker6_LONG'], 
                                                            row['Marker7_LONG'], row['Marker8_LONG'], row['Marker9_LONG'], row['Marker10_LONG'],
                                                            row['Marker11_LONG'], row['Marker12_LONG'], row['Marker13_LONG'], row['Marker14_LONG'],
                                                            row['Marker15_LONG'], row['Marker16_LONG'], row['Marker17_LONG'], row['Marker18_LONG'], 
                                                            row['Marker19_LONG'], row['Marker20_LONG']),axis=1))

In [28]:
ads = ads[['OUTAGE_ID', 'LAT', 'LONG', 'Min_Distance', 'Marker_Location']]

In [30]:
ads.head()

    OUTAGE_ID        LAT       LONG Min_Distance Marker_Location
0  2001317842  39.724871 -86.037147      6.27486              12
1  2001317865  39.896820 -86.145802       4.7429               3
2  2001317856  39.543034 -86.573913      1.89802              19
3  2001317899  39.787152 -86.252024      4.94615              11
4  2001317873  39.631311 -86.375051      5.98502              18

In [31]:
marker_count = ads.groupby(['Marker_Location'],as_index=False).agg({'OUTAGE_ID' : 'count'})

In [34]:
marker_count.sort_values(['OUTAGE_ID'],ascending=False,inplace=True)
print(ads.shape[0])
print(sum(marker_count.OUTAGE_ID))
print(ads.LAT.isnull().sum())
print(ads.shape[0] - sum(marker_count.OUTAGE_ID))
marker_count

19673
19514
159
159

    Marker_Location  OUTAGE_ID
7                 8       2999
6                 7       1958
11               12       1732
3                 4       1704
10               11       1679
2                 3       1638
14               15       1306
8                 9       1005
15               16        908
9                10        765
4                 5        712
5                 6        633
12               13        610
1                 2        444
17               18        378
13               14        377
16               17        331
18               19        142
19               20        139
0                 1         54

In [35]:
ads['Marker_Location'] = 'Marker' + ads['Marker_Location'].astype(str)

In [39]:
ads.Marker_Location.unique()

array(['Marker12', 'Marker3', 'Marker19', 'Marker11', 'Marker18',
       'Marker9', 'Marker5', 'Marker16', 'Marker10', 'Marker15',
       'Marker14', 'Marker7', 'Marker2', 'Marker4', 'Marker8', 'Marker13',
       'Marker1', 'Marker6', 'Marker17', 'Marker20', 'MarkerNone'],
      dtype=object)

In [ ]:
data1=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker1_storm_data.csv')
data2=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker2_storm_data.csv')
data3=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker3_storm_data.csv')
data4=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker4_storm_data.csv')
data5=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker5_storm_data.csv')
data6=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker6_storm_data.csv')
data7=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker7_storm_data.csv')
data8=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker8_storm_data.csv')
data9=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker9_storm_data.csv')
data10=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker10_storm_data.csv')
data11=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker11_storm_data.csv')
data12=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker12_storm_data.csv')
data13=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker13_storm_data.csv')
data14=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker14_storm_data.csv')
data15=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker15_storm_data.csv')
data16=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker16_storm_data.csv')
data17=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker17_storm_data.csv')
data18=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker18_storm_data.csv')
data19=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/Weather_Dark_Sky_USA_Indianapolis_Historical data_Storm data 2007-2019_location_specific_data_Marker19_storm_data.csv')
data20=pd.read_csv('C:/Users/sudheer.Bandla/Desktop/Outage restoration/DarkSky/storm/marker20.csv')

In [ ]:
data_final=pd.concat([data1,
data2,
data3,
data4,
data5,
data6,
data7,
data8,
data9,
data10,
data11,
data12,
data13,
data14,
data15,
data16,
data17,
data18,
data19,
data20],ignore_index=True)